logging:
  level:
    ROOT: DEBUG
    org.hibernate.SQL: DEBUG
    com.sixdee.user: DEBUG
    
spring:  devtools:
    restart:
      enabled: true
      additional-exclude: static/**    
  jackson:
    serialization:
      indent-output: true
  jpa:
    show-sql: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://10.0.14.66:3306/SMARTFREN_DMS?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true
    username: dmsuser
    password: dmsUser@123
    hikari:
      poolName: Hikari
      auto-commit: false
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
  
appconfig:
  logging:
    use-json-format: false # By default, logs are not in Json format
    logstash: # Forward logs to logstash over a socket, used by LoggingConfiguration
      enabled: false
      host: localhost
      port: 5000
      queue-size: 512     
  security:
   authentication:
      jwt:
        # This token must be encoded using Base64 and be at least 256 bits long (you can type `openssl rand -base64 64` on your command line to generate a 512 bits one)
        base64-secret: MTFkN2RkYjQ1NWM2N2ZlOTRkNmZmN2I4NmU2ZDI4MDAwMjYzMjAxM2Y0ZDJjNmIxM2E4MDk1NmViZDE3NWZjZDM0OTY4NmFiYTg1NmE4ZDJmNjVjYjY0ODE3NmQ4NTk5YmE2Yzg0ODM3NzU4ZjdjYmVhYmM1MmY2ZmNiYzE3ZjY=
        secret: sixdeejwt
  apiDocs:
    title: "DMS"
    description: "Hierarchy Service"
    version: "1.0.0"
  cache: # Cache configuration
    redis: # Redis configuration
      expiration: 3600 # By default objects stay 1 hour (in seconds) in the cache
      server: redis://10.0.14.140:6379
      cluster: false
      # server: redis://localhost:6379,redis://localhost:16379,redis://localhost:26379
      # cluster: true
    #hazelcast:
    #  timeToLiveSeconds: 1000
    #  server: localhost
        
    # By default CORS is disabled. Uncomment to enable.
  # cors:
  #   allowed-origins: "http://localhost:8100,http://localhost:9000"
  #   allowed-methods: "*"
  #   allowed-headers: "*"
  #   exposed-headers: "Authorization,Link,X-Total-Count,X-${jhipster.clientApp.name}-alert,X-${jhipster.clientApp.name}-error,X-${jhipster.clientApp.name}-params"
  #   allow-credentials: true
  #   max-age: 1800   
