server:
  port: 8081
  error:
    whitelabel:
      enabled: false
  servlet:
    context-path : /hierarchy
    session:
      cookie:
        http-only: true
      
logging:
  config: classpath:logback-spring.xml

management:
  endpoints:
    enabled-by-default: true
    endpoint:
      info:
        enabled: true
      shutdown:
        enabled: true
    shutdown:
      enabled: true
    web:
      expose: "*"
      exposure:
        include: "*"

endpoints:
  shutdown:
    enabled: true
    
spring:
  application:
    name: hierarchy-service
  autoconfigure:
    exclude: org.springframework.boot.actuate.autoconfigure.metrics.jdbc.DataSourcePoolMetricsAutoConfiguration
  profiles:
    active: #
    group:
      dev:
        - dev        
        # Uncomment to activate TLS for the dev profile
        #- tls
  jmx:
    enabled: false
  data:
    jpa:
      repositories:
        bootstrap-mode: deferred
  jpa:
    open-in-view: false
    properties:
      hibernate.jdbc.time_zone: UTC # Use UTC timezone to store in db
      hibernate.id.new_generator_mappings: true # configuration property which tells Hibernate that the underlying JDBC Connections already disabled the auto-commit mode.
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.region.factory_class: jcache
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      # modify batch size as necessary
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.query.fail_on_pagination_over_collection_fetch: true
      hibernate.query.in_clause_parameter_padding: true
#      hibernate.cache.region.factory_class: org.redisson.hibernate.RedissonRegionFactory
#      hibernate.cache.redisson.config: "/redisson.yaml"
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
  main:
    allow-bean-definition-overriding: true
  task:
   execution:
      thread-name-prefix: hierarchy-task-
      pool:
        core-size: 2
        max-size: 50
        queue-capacity: 10000
   scheduling:
      thread-name-prefix: hierarchy-scheduling-
      pool:
        size: 2
